# version: '3.8' - removed as it's obsolete

services:
  web:
    build: .
    ports:
      - "8080:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
    restart: always
    command: ["bash", "/app/scripts/entrypoint.sh"]
    networks:
      - palliative-care-network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - palliative-care-network

networks:
  palliative-care-network:
    driver: bridge

volumes:
  postgres_data:
